### ISSUE TITLE
Web UI

### ISSUE THREAD

**Issue by shandshellin** [spritsail/sonarr#5]
Web Ui seems very unstable, is this common to Sonarr or just this offshoot?

**Comment by Adam-Ant** [comment]
Hey. We're not aware of any unstableness with the web UI. What do you mean by this? Is the container crashing, is it not loading from time to time etc? A compose file (or docker run line), some logs from the sonarr container and any details about your environment (reverse proxy, spec of what you are running this on etc) would be helpful here - you've not given us much to go on to help you with!
